// Code generated by protoc-gen-go.
// source: citizens.proto
// DO NOT EDIT!

/*
Package citizens is a generated protocol buffer package.

It is generated from these files:
	citizens.proto

It has these top-level messages:
	Citizen
	GetRequest
	GetResponse
	SelectRequest
	SelectResponse
	CreateRequest
	CreateResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
*/
package citizens

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Citizen struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Fullname string `protobuf:"bytes,2,opt,name=fullname" json:"fullname,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *Citizen) Reset()                    { *m = Citizen{} }
func (m *Citizen) String() string            { return proto.CompactTextString(m) }
func (*Citizen) ProtoMessage()               {}
func (*Citizen) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Citizen) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Citizen) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *Citizen) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetResponse struct {
	Data *Citizen `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetResponse) GetData() *Citizen {
	if m != nil {
		return m.Data
	}
	return nil
}

type SelectRequest struct {
}

func (m *SelectRequest) Reset()                    { *m = SelectRequest{} }
func (m *SelectRequest) String() string            { return proto.CompactTextString(m) }
func (*SelectRequest) ProtoMessage()               {}
func (*SelectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type SelectResponse struct {
	Data []*Citizen `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *SelectResponse) Reset()                    { *m = SelectResponse{} }
func (m *SelectResponse) String() string            { return proto.CompactTextString(m) }
func (*SelectResponse) ProtoMessage()               {}
func (*SelectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SelectResponse) GetData() []*Citizen {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateRequest struct {
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type CreateResponse struct {
	Data *Citizen `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateResponse) GetData() *Citizen {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateRequest struct {
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type UpdateResponse struct {
	Data *Citizen `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateResponse) GetData() *Citizen {
	if m != nil {
		return m.Data
	}
	return nil
}

type DeleteRequest struct {
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DeleteResponse struct {
	Data *Citizen `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DeleteResponse) GetData() *Citizen {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Citizen)(nil), "citizens.Citizen")
	proto.RegisterType((*GetRequest)(nil), "citizens.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "citizens.GetResponse")
	proto.RegisterType((*SelectRequest)(nil), "citizens.SelectRequest")
	proto.RegisterType((*SelectResponse)(nil), "citizens.SelectResponse")
	proto.RegisterType((*CreateRequest)(nil), "citizens.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "citizens.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "citizens.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "citizens.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "citizens.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "citizens.DeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Citizenship service

type CitizenshipClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type citizenshipClient struct {
	cc *grpc.ClientConn
}

func NewCitizenshipClient(cc *grpc.ClientConn) CitizenshipClient {
	return &citizenshipClient{cc}
}

func (c *citizenshipClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/citizens.Citizenship/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *citizenshipClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error) {
	out := new(SelectResponse)
	err := grpc.Invoke(ctx, "/citizens.Citizenship/Select", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *citizenshipClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := grpc.Invoke(ctx, "/citizens.Citizenship/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *citizenshipClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := grpc.Invoke(ctx, "/citizens.Citizenship/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *citizenshipClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/citizens.Citizenship/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Citizenship service

type CitizenshipServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Select(context.Context, *SelectRequest) (*SelectResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterCitizenshipServer(s *grpc.Server, srv CitizenshipServer) {
	s.RegisterService(&_Citizenship_serviceDesc, srv)
}

func _Citizenship_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CitizenshipServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/citizens.Citizenship/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CitizenshipServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Citizenship_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CitizenshipServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/citizens.Citizenship/Select",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CitizenshipServer).Select(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Citizenship_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CitizenshipServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/citizens.Citizenship/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CitizenshipServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Citizenship_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CitizenshipServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/citizens.Citizenship/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CitizenshipServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Citizenship_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CitizenshipServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/citizens.Citizenship/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CitizenshipServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Citizenship_serviceDesc = grpc.ServiceDesc{
	ServiceName: "citizens.Citizenship",
	HandlerType: (*CitizenshipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Citizenship_Get_Handler,
		},
		{
			MethodName: "Select",
			Handler:    _Citizenship_Select_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Citizenship_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Citizenship_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Citizenship_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "citizens.proto",
}

func init() { proto.RegisterFile("citizens.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xdb, 0x44, 0xd3, 0x3a, 0xc1, 0x88, 0x43, 0xa5, 0x21, 0x27, 0x59, 0x28, 0x78, 0xea,
	0xa1, 0x16, 0x3c, 0x79, 0xaa, 0x50, 0xc4, 0x5b, 0xc4, 0xb3, 0xc4, 0x66, 0xc4, 0x85, 0x34, 0x89,
	0xd9, 0xcd, 0xc5, 0x3f, 0xe7, 0x5f, 0x13, 0x77, 0xbb, 0xc9, 0xae, 0x3d, 0x48, 0x6e, 0x99, 0x37,
	0xef, 0xbd, 0x0c, 0x5f, 0x08, 0x44, 0x3b, 0x2e, 0xf9, 0x17, 0x95, 0x62, 0x59, 0x37, 0x95, 0xac,
	0x70, 0x6a, 0x66, 0xf6, 0x04, 0x93, 0x8d, 0x7e, 0xc6, 0x08, 0x3c, 0x9e, 0xc7, 0xe3, 0xeb, 0xf1,
	0xcd, 0x59, 0xea, 0xf1, 0x1c, 0x13, 0x98, 0xbe, 0xb7, 0x45, 0x51, 0x66, 0x7b, 0x8a, 0x3d, 0xa5,
	0x76, 0x33, 0xce, 0xe0, 0x94, 0xf6, 0x19, 0x2f, 0x62, 0x5f, 0x2d, 0xf4, 0xc0, 0x16, 0x00, 0x5b,
	0x92, 0x29, 0x7d, 0xb6, 0x24, 0x24, 0xce, 0x61, 0xd2, 0x0a, 0x6a, 0x5e, 0xbb, 0xd2, 0xe0, 0x77,
	0x7c, 0xcc, 0xd9, 0x1a, 0x42, 0x65, 0x13, 0x75, 0x55, 0x0a, 0xc2, 0x05, 0x9c, 0xe4, 0x99, 0xcc,
	0x94, 0x29, 0x5c, 0x5d, 0x2e, 0xbb, 0x5b, 0x0f, 0x87, 0xa5, 0x6a, 0xcd, 0x2e, 0xe0, 0xfc, 0x99,
	0x0a, 0xda, 0x99, 0x7e, 0x76, 0x07, 0x91, 0x11, 0x8e, 0x9a, 0xfc, 0x7f, 0x9a, 0x36, 0x0d, 0x65,
	0x92, 0xac, 0x26, 0x23, 0x0c, 0xbe, 0xe9, 0xa5, 0xce, 0xdd, 0x26, 0x23, 0x0c, 0x6e, 0x7a, 0xa0,
	0x82, 0x9c, 0x26, 0x23, 0x0c, 0x6a, 0x5a, 0x7d, 0x7b, 0x10, 0x1e, 0x14, 0xf1, 0xc1, 0x6b, 0x5c,
	0x83, 0xbf, 0x25, 0x89, 0xb3, 0xde, 0xdf, 0x7f, 0xa3, 0xe4, 0xea, 0x8f, 0xaa, 0x5f, 0xc5, 0x46,
	0x78, 0x0f, 0x81, 0x86, 0x8b, 0xf3, 0xde, 0xe2, 0xf0, 0x4f, 0xe2, 0xe3, 0x85, 0x1d, 0xd7, 0x44,
	0xed, 0xb8, 0x03, 0xdd, 0x8e, 0xbb, 0xf0, 0x75, 0x5c, 0x63, 0xb4, 0xe3, 0x0e, 0x69, 0x3b, 0xee,
	0x12, 0xd7, 0x71, 0xcd, 0xce, 0x8e, 0x3b, 0x78, 0xed, 0xb8, 0x8b, 0x99, 0x8d, 0xde, 0x02, 0xf5,
	0x93, 0xdc, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xae, 0xcc, 0x69, 0x7c, 0x36, 0x03, 0x00, 0x00,
}
